navn = input("Hva er ditt navn? ")
adresse = input("Hva er din adresse? ")
postnummer = input("Hva er ditt postnummer og poststed? ")
print(navn + "s" + " adresse er:")
print()
print(navn)
print(adresse)
print(postnummer)
